### ISSUE TITLE
Avoid Repeating Styles when possible

### ISSUE THREAD

**Issue by zannain** [vladinskiID/prj-rev-bwfs-tea-cozy#2]
[Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). This is an important programming principle. If you find yourself repeating certain styles this is an indication that you can simplify your stylesheet by making use of CSS classes.

An alternative to [applying](https://github.com/vladinskiID/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L39-L41) the following styles multiple times. 

```css
  align-items: center;
  margin-left: auto;
  margin-right: auto;
```
**Alternatives**

1. Using a less specific selector may be more appropriate
```css
body {
     margin-left: auto;
     margin-right: auto;
}
```
2. You can also create a style-specific class

```css
.center_align {
  align-items: center;
  margin-left: auto;
  margin-right: auto;
 }
```
Now you can give multiple element tags a class attribute of `center_alight` and they will all receive this common style. This is in fact how CSS libraries such as [Bootstrap](https://getbootstrap.com/) work. 

3. [Using CSS Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)

```css
:root {
    --default-align: center;
}

#paint {
     align-items: var(--default-align);
}
```

With any of these approaches, it's easy to update a style simultaneously by modifying that variable or the `.center_align` selector and the entire page is updated.
